### ISSUE TITLE
Tag update to 0.0.4 version

### ISSUE THREAD

**Issue by cristianoliveira** [jonathansp/jquery-serializeFields#16]
Please update tag for last version. That way bower can show the right version.
:+1:

**Comment by cristianoliveira** [comment]
And yes... I know... Is Brazil Valentine's day and I opened an issue on Github hahaahah

![LOOOL](http://www.quickmeme.com/img/13/139e1e24e4563e65a4684885c035192402ae72fb05b5e42ad84509ef2137e212.jpg)

**Comment by jonathansp** [comment]
Sorry for (big) delay.

**Comment by cristianoliveira** [comment]
Took too much time than I've already found a girl! LOOL :+1:

(Seriously)
No worries.
Thanks! Man!
