### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by isitgeorge** [jonathansp/jquery-serializeFields#18]
Not sure if its something to do with my setup, or if there is an actual issue with IE 11 support but..

the `serialiserializeFields` method gathers all the data into a JSON object, but doesn't group by the `fieldset` names. All the keys are at the same level.

Anybody had experience with this? Cheers

P.S. a client uses IE not me!

**Comment by jonathansp** [comment]
Hi @isitgeorge, thanks for reporting it. Could please share which version of jQuery are you using?

**Comment by isitgeorge** [comment]
Of course - 2.2.0

**Comment by isitgeorge** [comment]
Investigated this a bit just incase anyone else has this issue. There seems to be a bug in IE with disabled/enabled fieldsets, and the jQuery selector seems to fail.

In my case the fieldsets were always enabled so I was able to simply use `fieldset_selector: "fieldset"` instead of the default `fieldset_selector: "fieldset:enabled"`

```
$(this.refs.entry).serializeFields({
    fieldset_selector: "fieldset"
);
```

Cheers,
